services:
  # Backend - FastAPI
  - type: web
    name: ifc-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifc-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6

  # Frontend - React
  - type: static
    name: ifc-frontend-react
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  # Frontend - Streamlit
  - type: web
    name: ifc-frontend-streamlit
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app/app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifc-database
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.6

databases:
  - name: ifc-database
    plan: free
    databaseName: ifc_monitoring
    user: ifc_user

